// Top 100 cryptocurrencies by market cap
export const TOP_COINS = [
  { id: "bitcoin", symbol: "BTC", name: "Bitcoin" },
  { id: "ethereum", symbol: "ETH", name: "Ethereum" },
  { id: "tether", symbol: "USDT", name: "Tether" },
  { id: "binancecoin", symbol: "BNB", name: "BNB" },
  { id: "solana", symbol: "SOL", name: "Solana" },
  { id: "usd-coin", symbol: "USDC", name: "USD Coin" },
  { id: "ripple", symbol: "XRP", name: "XRP" },
  { id: "cardano", symbol: "ADA", name: "Cardano" },
  { id: "dogecoin", symbol: "DOGE", name: "Dogecoin" },
  { id: "avalanche-2", symbol: "AVAX", name: "Avalanche" },
  { id: "tron", symbol: "TRX", name: "TRON" },
  { id: "polkadot", symbol: "DOT", name: "Polkadot" },
  { id: "chainlink", symbol: "LINK", name: "Chainlink" },
  { id: "matic-network", symbol: "MATIC", name: "Polygon" },
  { id: "wrapped-bitcoin", symbol: "WBTC", name: "Wrapped Bitcoin" },
  { id: "shiba-inu", symbol: "SHIB", name: "Shiba Inu" },
  { id: "dai", symbol: "DAI", name: "Dai" },
  { id: "litecoin", symbol: "LTC", name: "Litecoin" },
  { id: "bitcoin-cash", symbol: "BCH", name: "Bitcoin Cash" },
  { id: "uniswap", symbol: "UNI", name: "Uniswap" },
  { id: "cosmos", symbol: "ATOM", name: "Cosmos Hub" },
  { id: "ethereum-classic", symbol: "ETC", name: "Ethereum Classic" },
  { id: "stellar", symbol: "XLM", name: "Stellar" },
  { id: "monero", symbol: "XMR", name: "Monero" },
  { id: "okb", symbol: "OKB", name: "OKB" },
  { id: "filecoin", symbol: "FIL", name: "Filecoin" },
  { id: "aptos", symbol: "APT", name: "Aptos" },
  { id: "near", symbol: "NEAR", name: "NEAR Protocol" },
  { id: "hedera-hashgraph", symbol: "HBAR", name: "Hedera" },
  { id: "vechain", symbol: "VET", name: "VeChain" },
  { id: "lido-dao", symbol: "LDO", name: "Lido DAO" },
  { id: "internet-computer", symbol: "ICP", name: "Internet Computer" },
  { id: "arbitrum", symbol: "ARB", name: "Arbitrum" },
  { id: "optimism", symbol: "OP", name: "Optimism" },
  { id: "the-graph", symbol: "GRT", name: "The Graph" },
  { id: "mantle", symbol: "MNT", name: "Mantle" },
  { id: "immutable-x", symbol: "IMX", name: "Immutable" },
  { id: "algorand", symbol: "ALGO", name: "Algorand" },
  { id: "quant-network", symbol: "QNT", name: "Quant" },
  { id: "aave", symbol: "AAVE", name: "Aave" },
  { id: "maker", symbol: "MKR", name: "Maker" },
  { id: "fantom", symbol: "FTM", name: "Fantom" },
  { id: "the-sandbox", symbol: "SAND", name: "The Sandbox" },
  { id: "stacks", symbol: "STX", name: "Stacks" },
  { id: "elrond-erd-2", symbol: "EGLD", name: "MultiversX" },
  { id: "injective-protocol", symbol: "INJ", name: "Injective" },
  { id: "theta-token", symbol: "THETA", name: "Theta Network" },
  { id: "axie-infinity", symbol: "AXS", name: "Axie Infinity" },
  { id: "eos", symbol: "EOS", name: "EOS" },
  { id: "flow", symbol: "FLOW", name: "Flow" },
  { id: "tezos", symbol: "XTZ", name: "Tezos" },
  { id: "kucoin-shares", symbol: "KCS", name: "KuCoin" },
  { id: "decentraland", symbol: "MANA", name: "Decentraland" },
  { id: "neo", symbol: "NEO", name: "NEO" },
  { id: "synthetix-network-token", symbol: "SNX", name: "Synthetix" },
  { id: "bitdao", symbol: "BIT", name: "BitDAO" },
  { id: "gala", symbol: "GALA", name: "Gala" },
  { id: "curve-dao-token", symbol: "CRV", name: "Curve DAO" },
  { id: "frax", symbol: "FRAX", name: "Frax" },
  { id: "chiliz", symbol: "CHZ", name: "Chiliz" },
  { id: "pancakeswap-token", symbol: "CAKE", name: "PancakeSwap" },
  { id: "zcash", symbol: "ZEC", name: "Zcash" },
  { id: "kava", symbol: "KAVA", name: "Kava" },
  { id: "1inch", symbol: "1INCH", name: "1inch" },
  { id: "compound-governance-token", symbol: "COMP", name: "Compound" },
  { id: "ethereum-name-service", symbol: "ENS", name: "Ethereum Name Service" },
  { id: "helium", symbol: "HNT", name: "Helium" },
  { id: "conflux-token", symbol: "CFX", name: "Conflux" },
  { id: "woo-network", symbol: "WOO", name: "WOO Network" },
  { id: "gmx", symbol: "GMX", name: "GMX" },
  { id: "basic-attention-token", symbol: "BAT", name: "Basic Attention Token" },
  { id: "arweave", symbol: "AR", name: "Arweave" },
  { id: "pepe", symbol: "PEPE", name: "Pepe" },
  { id: "floki", symbol: "FLOKI", name: "FLOKI" },
  { id: "mina-protocol", symbol: "MINA", name: "Mina Protocol" },
  { id: "dash", symbol: "DASH", name: "Dash" },
  { id: "zilliqa", symbol: "ZIL", name: "Zilliqa" },
  { id: "iota", symbol: "IOTA", name: "IOTA" },
  { id: "thorchain", symbol: "RUNE", name: "THORChain" },
  { id: "ecash", symbol: "XEC", name: "eCash" },
  { id: "nexo", symbol: "NEXO", name: "NEXO" },
  { id: "ravencoin", symbol: "RVN", name: "Ravencoin" },
  { id: "enjincoin", symbol: "ENJ", name: "Enjin Coin" },
  { id: "loopring", symbol: "LRC", name: "Loopring" },
  { id: "convex-finance", symbol: "CVX", name: "Convex Finance" },
  { id: "celo", symbol: "CELO", name: "Celo" },
  { id: "terra-luna", symbol: "LUNA", name: "Terra Luna Classic" },
  { id: "oasis-network", symbol: "ROSE", name: "Oasis Network" },
  { id: "sushi", symbol: "SUSHI", name: "Sushi" },
  { id: "balancer", symbol: "BAL", name: "Balancer" },
  { id: "qtum", symbol: "QTUM", name: "Qtum" },
  { id: "skale", symbol: "SKL", name: "SKALE" },
  { id: "ankr", symbol: "ANKR", name: "Ankr Network" },
  { id: "celsius-degree-token", symbol: "CEL", name: "Celsius Network" },
  { id: "gatechain-token", symbol: "GT", name: "GateToken" },
  { id: "holo", symbol: "HOT", name: "Holo" },
  { id: "amp-token", symbol: "AMP", name: "Amp" },
  { id: "waxp", symbol: "WAXP", name: "WAX" },
  { id: "harmony", symbol: "ONE", name: "Harmony" },
];
